# Generated by Django 2.2.4 on 2019-10-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_car_owner'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cars_owned',
            field=models.ManyToManyField(blank=True, to='cars.Car'),
        ),
    ]
