# Generated by Django 2.2.4 on 2019-11-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cars_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_cars',
            field=models.CharField(default='[]', max_length=512),
        ),
    ]
