# Generated by Django 2.2.4 on 2019-11-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_auto_20191112_1422'),
        ('users', '0003_user_favourite_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cars_owned',
            field=models.ManyToManyField(blank=True, related_name='owned', to='cars.Car'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_cars',
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_cars',
            field=models.ManyToManyField(blank=True, related_name='favourite', to='cars.Car'),
        ),
    ]
