# Generated by Django 2.2.4 on 2020-02-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200201_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
