# Generated by Django 2.2.4 on 2019-08-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=50)),
                ('engine_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=550, null=True)),
            ],
        ),
    ]
