# Generated by Django 2.2.4 on 2019-08-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pictures',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
