# Generated by Django 2.2.4 on 2019-08-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_extracategory_extras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extras',
            new_name='Extra',
        ),
    ]
