# Generated by Django 2.2.4 on 2019-08-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_extras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='extras',
        ),
    ]
