# Generated by Django 2.2.4 on 2019-08-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_car_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
                ('extra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Extra')),
            ],
        ),
    ]
