# Generated by Django 2.2.4 on 2019-08-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_extras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarExtra',
        ),
    ]
