# Generated by Django 2.2.4 on 2019-08-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_delete_carextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='new',
        ),
    ]
