# Generated by Django 2.2.4 on 2019-08-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_car_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='extras',
            field=models.ManyToManyField(blank=True, to='cars.Extra'),
        ),
    ]
