# Generated by Django 2.2.4 on 2019-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20190820_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='pictures',
        ),
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
