# Generated by Django 2.2.4 on 2019-08-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_car_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='pictures',
        ),
    ]
