# Generated by Django 2.2.4 on 2019-08-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_remove_car_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
