# Generated by Django 2.2.4 on 2019-08-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_auto_20190820_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='picture',
        ),
        migrations.AddField(
            model_name='car',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='cars.Picture'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
