# Generated by Django 2.2.4 on 2019-08-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_auto_20190821_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='extras',
        ),
    ]
