# Generated by Django 2.2.4 on 2019-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_remove_car_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='extras',
            field=models.ManyToManyField(blank=True, to='cars.Extra'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='zip_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Safety',
        ),
    ]
