# Generated by Django 2.2.4 on 2019-08-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_auto_20190821_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='extras',
        ),
    ]
