# Generated by Django 2.2.4 on 2019-10-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_car_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='consumption',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(blank=True, max_length=2, null=True),
        ),
    ]
