# Generated by Django 2.2.4 on 2019-10-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_auto_20191022_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
