# Generated by Django 2.2.4 on 2019-11-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0032_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='included_km',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='max_rent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='min_rent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='monthly_discount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='pets',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_extra_km',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='smoking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='weekly_discount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
