# Generated by Django 2.2.4 on 2020-01-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('cars', '0033_auto_20191112_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='reservations',
            field=models.ManyToManyField(blank=True, to='reservations.Reservation'),
        ),
    ]
