# Generated by Django 2.2.4 on 2020-01-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0035_auto_20200106_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='reservations',
        ),
    ]
