# Generated by Django 2.2.4 on 2020-01-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0036_remove_car_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='min_rent',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
