# Generated by Django 2.2.4 on 2020-01-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0037_auto_20200127_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='max_rent',
        ),
        migrations.RemoveField(
            model_name='car',
            name='min_rent',
        ),
    ]
