# Generated by Django 2.2.4 on 2020-01-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0039_auto_20200127_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=200),
        ),
    ]
