# Generated by Django 2.2.4 on 2020-01-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0040_auto_20200127_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='max_rent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='min_rent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='consumption',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='included_km',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='monthly_discount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_extra_km',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='weekly_discount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='zip_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
