# Generated by Django 2.2.4 on 2020-01-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0043_auto_20200127_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='max_rent',
        ),
        migrations.RemoveField(
            model_name='car',
            name='min_rent',
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.PositiveSmallIntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='included_km',
            field=models.PositiveSmallIntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='monthly_discount',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='weekly_discount',
            field=models.PositiveSmallIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='zip_code',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
