# Generated by Django 2.2.4 on 2020-01-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0044_auto_20200127_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=8.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=32, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_extra_km',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=5),
            preserve_default=False,
        ),
    ]
