# Generated by Django 2.2.4 on 2020-01-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0045_auto_20200127_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='consumption',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
